language: bash
sudo: false
dist: xenial
install: true

addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - luarocks
    - libzip2
    - libzip-dev

install:
  - luarocks install --local love-release

env:
  global:
  - secure: ${github_token}
  
script:
  - love-release test/ src/
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh web || ./build.sh" # web only for tags

after_success: "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy $TRAVIS_REPO_SLUG"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${github_token}
  file:
  - target/haru-project.love
  - target/haru-project-win.zip
  - target/haru-project-web.zip
  on:
    tags: true