language: bash
sudo: false
install: true

addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - libplist-utils

env:
  global:
  - secure: ${github_token}

before_script:
  - find . -iname "*.lua" | xargs luac -p || { echo 'luac parse test failed' ; exit 1; }

script:
  - ./build.sh create
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh mac || exit 0"
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh win32 || exit 0"
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh win64 || exit 0"
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh web || exit 0"

after_success: "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy $TRAVIS_REPO_SLUG"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${github_token}
  file:
  - target/haru-project.love
  - target/haru-project-mac.zip
  - target/haru-project-win32.zip
  - target/haru-project-win64.zip
  - target/haru-project-web.zip
  on:
    tags: true